### ISSUE TITLE
Server closing connection

### ISSUE THREAD

**Issue by telion2** [interactionlab/NLATool#106]
It seems that for longer runs the server comes across some unhandled errors. Not sure why. 
Is it because of open connection with the DB or Socket.io that need to be closed? 
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/telion2/NLATool/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/home/telion2/NLATool/node_modules/mysql/lib/Connection.js:109:28)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at Connection._handleProtocolError (/home/telion2/NLATool/node_modules/mysql/lib/Connection.js:433:8)
    at Protocol.emit (events.js:180:13)
    at Protocol._delegateError (/home/telion2/NLATool/node_modules/mysql/lib/protocol/Protocol.js:392:10)
    at Protocol.end (/home/telion2/NLATool/node_modules/mysql/lib/protocol/Protocol.js:117:8)
    at Socket.<anonymous> (/home/telion2/NLATool/node_modules/mysql/lib/Connection.js:109:28)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:114:19)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by telion2** [comment]
Since this is about a extern Server and has nothing to do with the coding o this app I will close this issue.
